### ISSUE TITLE
 python neural_net.py   IOError: [Errno 2]

### ISSUE THREAD

**Issue by molyswu** [ArifSohaib/tensorflow-sentiment-analysis-and-data-read#1]
I try to run : # python neural_net.py 
Bug as below:
testing net
Traceback (most recent call last):
  File "neural_net.py", line 262, in <module>
    test_neural_network()
  File "neural_net.py", line 195, in test_neural_network
    with open('../lexicon.pickle','rb') as f:
IOError: [Errno 2] No such file or directory: '../lexicon.pickle'

Thanks you for your help!

**Comment by ArifSohaib** [comment]
sorry for the late reply.
I forgot to add the create_lexicon function earlier.
You need to run this to create the lexicon before running the neural_net.py
